import random


''' pw_generator is a function used to
    generate a specific length of strong and secure password for users,
    the argument 'passlen' is an integer input from the user'''
def pw_generator(passlen):

    
    ''' s is a string containing all the loewer and upper case letters,
        numbers and charactors'''
    s='abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()+-*/<>?,.;:'


    '''A new password is generated by selecting a number equaling to passlen
        of charactors from the string s'''
    password=(''.join(random.sample(s,passlen)))

    return password


'''pw_save is a function adoptet to save the user's 'accountName and password
    into a file called coolThings.txt, if the file is not existing in the
    user's device, a new file
    called coolThings.txt will be created automatically'''
def pw_save(accountName,password):

    ''''''
    infor=str(accountName)+' :   '+str(password)+'\n'
    
    with open('coolThings.txt','a+') as file:
        appender=file.writelines(infor)

'''pw_main is the main function used to execute the application'''
def pw_main():
    passlen=int(input('What the length of your password? '))
    p1=pw_generator(passlen)
    print(p1)
    accountName=input('Enter the account that your password belong to: ')
    pw_save(accountName,p1)

pw_main()
